export const INCREMENT_NUMBER = "INCREMENT_NUMBER";
export const DECREMENT_NUMBER = "DECREMENT_NUMBER";


export const PRODUCT_LIST="PRODUCT_LIST";
export const PRODUCT_LIST_FETCHING="PRODUCT_LIST_FETCHING";
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS";


export const FILTER_MODAL="FILTER_MODAL";
export const CART_DISPLAY="CART_DISPLAY";


export const FILTERED_PRODUCT="FILTERED_PRODUCT";

export const CART_PRODUCT="CART_PRODUCT";
export const TOTAL_PRICE="TOTAL_PRICE";

export const PRODUCT_DETAIL="PRODUCT_DETAIL";